# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=750)),
                ('descrizione', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Categoria'),
        ),
    ]
