# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20181116_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='public_map',
            field=models.BooleanField(default=False),
        ),
    ]
