# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_categoria_public_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='visibile',
            field=models.BooleanField(default=True),
        ),
    ]
